import React, { useEffect, useMemo, useState } from "react";
import { api, fmtTime } from "../api.js";
import { Empty, Modal, PageHead, useToast } from "../components/common.jsx";

const parse = (raw, fallback) => { try { return JSON.parse(raw); } catch { return fallback; } };

export default function DataPage() {
  const [contents, setContents] = useState([]);
  const [reviews, setReviews] = useState([]);
  const [detail, setDetail] = useState(null);
  const [creating, setCreating] = useState(false);
  const toast = useToast();
  const load = async () => { try { const [all, rs] = await Promise.all([api.get("/api/contents?status=published"), api.get("/api/reviews")]); setContents(all); setReviews(rs); } catch (e) { toast.show(e.message); } };
  useEffect(() => { load(); }, []);
  const totals = useMemo(() => contents.reduce((acc, c) => { const s = parse(c.stats_json, {}); acc.views += Number(s.views) || 0; acc.likes += Number(s.likes) || 0; acc.collects += Number(s.collects) || 0; acc.comments += Number(s.comments) || 0; acc.leads += Number(s.new_leads) || 0; return acc; }, { views: 0, likes: 0, collects: 0, comments: 0, leads: 0 }), [contents]);
  async function generate() { setCreating(true); try { await api.post("/api/reviews/generate", {}); toast.show("本周复盘已生成；结论可直接用作下一批选题参考。"); load(); } catch (e) { toast.show(e.message); } finally { setCreating(false); } }
  return <div><PageHead title="数据" sub="先录入真实发布数据，再生成复盘。OneDesk 不会伪造曝光或转化。"><button className="btn btn-primary" disabled={creating} onClick={generate}>{creating ? "复盘生成中…" : "生成本周复盘"}</button></PageHead>{toast.node}<div className="grid grid-cols-5 gap-4 mb-6">{[["已发布", contents.length, "篇"], ["浏览", totals.views, "次"], ["收藏", totals.collects, "次"], ["评论", totals.comments, "条"], ["录入线索", totals.leads, "条"]].map(([name, value, unit]) => <div className="card px-4 py-4" key={name}><div className="text-xs text-[#a39e92]">{name}</div><div className="font-title text-2xl font-semibold mt-2">{value}<span className="text-xs font-sans text-[#a39e92] ml-1">{unit}</span></div></div>)}</div><div className="grid grid-cols-5 gap-5"><section className="col-span-3"><div className="flex items-center justify-between mb-3"><h2 className="font-title text-lg font-semibold">发布数据录入</h2><p className="text-xs text-[#a39e92]">点击一篇笔记录入发布后的真实数据</p></div><div className="card overflow-hidden">{contents.length === 0 ? <Empty text="暂无已发布内容。内容通过后，复制清单并在小红书人工发布，再回填链接即可在这里复盘。" /> : <table className="w-full text-sm"><thead className="bg-[#f7f4ee] text-xs text-[#6b675e]"><tr><th className="text-left p-4 font-medium">笔记</th><th className="text-right p-4 font-medium">浏览</th><th className="text-right p-4 font-medium">收藏</th><th className="text-right p-4 font-medium">评论</th><th className="text-right p-4 font-medium">线索</th></tr></thead><tbody>{contents.map((c) => <ContentStatRow key={c.id} content={c} onOpen={() => setDetail(c.id)} />)}</tbody></table>}</div></section><section className="col-span-2"><h2 className="font-title text-lg font-semibold mb-3">周复盘</h2><div className="space-y-3">{reviews.length === 0 ? <div className="card px-5 py-8 text-center text-sm text-[#a39e92]">完成至少一篇发布登记后，生成第一份周复盘。</div> : reviews.map((r) => <button key={r.id} className="card w-full text-left px-5 py-4 hover:border-[#b9b1a4]" onClick={() => setDetail({ review: r })}><div className="flex justify-between text-xs text-[#a39e92]"><span>周复盘</span><span>{r.week_start}</span></div><p className="mt-2 text-sm leading-relaxed line-clamp-3 whitespace-pre-wrap">{r.summary_md}</p><p className="mt-3 text-xs text-[#c2401f]">查看结论 →</p></button>)}</div></section></div>{typeof detail === "number" && <StatsModal content={contents.find((c) => c.id === detail)} toast={toast} onClose={() => setDetail(null)} onDone={() => { setDetail(null); load(); }} />}{detail?.review && <ReviewModal review={detail.review} onClose={() => setDetail(null)} />}</div>;
}

function ContentStatRow({ content, onOpen }) { const s = parse(content.stats_json, {}); return <tr onClick={onOpen} className="border-t border-[#e3ddd1] hover:bg-[#fdfbf7] cursor-pointer"><td className="p-4 max-w-96"><div className="font-medium truncate">{content.title}</div><div className="text-xs text-[#a39e92] mt-1">{content.topic_type} · {fmtTime(content.publish_time)}</div></td><td className="p-4 text-right">{s.views || 0}</td><td className="p-4 text-right">{s.collects || 0}</td><td className="p-4 text-right">{s.comments || 0}</td><td className="p-4 text-right font-medium text-[#c2401f]">{s.new_leads || 0}</td></tr>; }

function StatsModal({ content, toast, onClose, onDone }) {
  const initial = parse(content.stats_json, {});
  const [stats, setStats] = useState({ views: initial.views || "", likes: initial.likes || "", collects: initial.collects || "", comments: initial.comments || "", new_leads: initial.new_leads || "" });
  const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); try { await api.patch(`/api/contents/${content.id}`, { stats: Object.fromEntries(Object.entries(stats).map(([k, v]) => [k, Math.max(0, Number(v) || 0)])) }); toast.show("发布数据已保存"); onDone(); } catch (e) { toast.show(e.message); } finally { setSaving(false); } }
  return <Modal open onClose={onClose} title="录入发布数据"><p className="font-medium text-sm leading-relaxed mb-4">{content.title}</p><div className="grid grid-cols-2 gap-3">{[["views", "浏览量"], ["likes", "点赞"], ["collects", "收藏"], ["comments", "评论"], ["new_leads", "该笔记新增线索"]].map(([key, label]) => <label key={key} className="block"><span className="text-xs text-[#6b675e]">{label}</span><input className="input mt-1" type="number" min="0" value={stats[key]} onChange={(e) => setStats({ ...stats, [key]: e.target.value })} /></label>)}</div><div className="flex justify-end gap-2 mt-5"><button className="btn btn-ghost" onClick={onClose}>取消</button><button className="btn btn-primary" disabled={saving} onClick={save}>{saving ? "保存中…" : "保存数据"}</button></div></Modal>;
}

function ReviewModal({ review, onClose }) { const keep = parse(review.keep_writing_json, []); const stop = parse(review.stop_writing_json, []); const next = parse(review.next_keywords_json, []); return <Modal open onClose={onClose} title={`${review.week_start} 周复盘`} wide><div className="grid grid-cols-3 gap-5"><section className="col-span-3 rounded-md bg-[#f7f4ee] p-5 whitespace-pre-wrap leading-relaxed text-sm">{review.summary_md}</section><ReviewList title="下周继续写" items={keep} empty="尚无足够数据，优先保持搜索型与避坑型内容的稳定产出。" accent="text-[#5c6f52]" /><ReviewList title="停止或改写" items={stop} empty="暂无需要停止的内容；继续收集真实数据。" accent="text-[#b07d2b]" /><ReviewList title="下批选题线索" items={next} empty="评论区高频问题会在这里沉淀为下一批关键词。" accent="text-[#c2401f]" /></div></Modal>; }
function ReviewList({ title, items, empty, accent }) { return <section><h3 className={`font-medium ${accent}`}>{title}</h3>{items.length ? <ul className="mt-3 space-y-2 text-sm text-[#6b675e]">{items.map((x, i) => <li key={i} className="leading-relaxed">• {x}</li>)}</ul> : <p className="mt-3 text-xs leading-relaxed text-[#a39e92]">{empty}</p>}</section>; }
